language: node_js
node_js:
  - 5.9
env:
  global:
  - secure: "lkYTOt8ERqmvhqhEMoYO1m3aTBFKZ12kdwH6Jr/+zW0wA91Q308lMqs1mJRFohi/54GFsfdwdColstfxc+EgnFyxJYgoS25I2UJxRgsqIkqcbLpp4APh1Q715aRQ2rYsOg/gUgxhl0AlYr9qIliubKNqReWwN8Mv2oox7yLsjNs4zDUKVu1ZomcM6ysPlcQxFqEZrdCpTkRqn3XHaBqjATuIrTmQKs085wDmOBDPlzvKozcsQxY8j6WsDRwKviKxX14BBop0ZbeDBzapWEHwGHOq5vDTHLmC49CMwb4PtTYbHPf3Z2pdMBZWhnxktd1u3TgwQF7C14nnURgIEmC+GZftjJtpsxvpbC8mx/ixg6/XjIkIkADt0gXj58lXeB/S9G5BDseKXUAPW1mQbkWUxwBSms/fxoUxhXe1GnIBEt1KgJUkvQ2Nio8krpDSTNPx+XnOMyRryqRA3NGl1d4tNDaVhSrcJjR1YV0jCDMDjOZITQaniFuntKMgS0V9Uxzc72yROEXKBWa6UtWi08DFLPwn5prbHYqXZVppAXjUTTpX6lX0rdZ5WnEqze9krJ8xx3KwqquURSK/hxCXtxBU2K99theCfh/QidjKxyI04kLUz8EGhrWATN6D7w/uNaGv9EwMoSthaQrAUlivCFeKqhbur/PTDQqr+ESd4n2LeKc="
